### ISSUE TITLE
no access to http://www.ansibleworks.com/docs/playbooks_variables.html#id26

### ISSUE THREAD

**Issue by fex01** [weareinteractive/ansible-git#2]
Hi guys,

In your README and in your defaults/main file for weareinteractive.git you mention
```
# For more information about default variables see:
# http://www.ansibleworks.com/docs/playbooks_variables.html#id26
```

Sadly that URL is 403 - forbidden. Please either link a public accessible information source or delete that remark...

(I would strongly prefer the first option - your roles variables could really use additional information about how to use them...)

BR,
fex

**Comment by franklinkim** [comment]
Thanks, fixed the link and PRs are always welcome!
