### ISSUE TITLE
[DEPRECATION WARNING] for task "Installing SSH key"

### ISSUE THREAD

**Issue by fex01** [weareinteractive/ansible-git#3]
Warning: "[DEPRECATION WARNING]: evaluating u'git_key' as a bare variable, this behaviour
 will go away and you might need to add |bool to the expression in the future. 
Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be 
removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg."

Solution: change line 'when: git_key' to 'when: git_key|length > 0'

**Comment by fex01** [comment]
Applies also to task 'Installing SSH key'

**Comment by fex01** [comment]
My fix fails for undefined git_key

**Comment by fex01** [comment]
new proposal: change line 'when: git_key' to 'when: git_key is defined'

**Comment by franklinkim** [comment]
THX
