### ISSUE TITLE
Using 'Installing SSH key' results in an invalid key file

### ISSUE THREAD

**Issue by fex01** [weareinteractive/ansible-git#5]
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/***/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/***/.local/lib/python2.7/site-packages/ansible
  executable location = /home/***/.local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

host: docker.io/pycontribs/debian:latest

Using the task 'Installing SSH key' results in an invalid key file and the error message 'Load key \"/etc/ssh/ssh_git.key\": invalid format' when trying to use said key.

The reason for that seems to be the first line of the template file '# {{ ansible_managed }}' wich results in the first line # Ansible managed: Do NOT edit this file manually inside the key file.
Deleting that Ansible line in the key file results in a valid key file.

Proposal: using the same deploy mechanism for private key files as in the weareinteractive.users role might avoid this issue (weareinteractive.users doesn't use a template file to deploy the private key).

```
# Ansible managed: Do NOT edit this file manually
-----BEGIN OPENSSH PRIVATE KEY-----
***
-----END OPENSSH PRIVATE KEY-----
```

**Comment by franklinkim** [comment]
THX
